##############################################################
# Global server configuration
##############################################################
port: "3010"

##############################################################
# Database
##############################################################
database:
  host: localhost
  port: 5432
  user: postgres 
  password: postgres 
  name: poop 
  ssl: disable #require, verify-full, verify-ca, disable  

##############################################################
# Logger 
##############################################################
logger:
  format: json 
  level: info 
  path: logs/poop.log 
